F95 = gfortran

FFLAGS	      = -g -w

CFLAGS	      = 

DEST	      = objects

EXTHDRS	      =

HDRS	      =

INSTALL	      = install

LD	      = gfortran

LDFLAGS	      = 

LIBS	      =

MAKEFILE      = Makefile

OBJS	      = objects/vr.o \
		objects/les.o \
		objects/archivr.o \
 		objects/omdnewt.o \
 		objects/omdgam.o \
 		objects/omdpset.o \
 		objects/omdflux.o \
 		objects/omderr.o \
 		objects/omdresa.o \
 		objects/omdresb.o \
 		objects/omdresd.o \
 		objects/omdreset.o \
 		objects/omanewt.o \
 		objects/omagam.o \
 		objects/omapset.o \
 		objects/omaflux.o \
 		objects/omaerr.o \
 		objects/omaresa.o \
 		objects/omaresb.o \
 		objects/omaresd.o \
 		objects/omareset.o \
 		objects/imdnewt.o \
 		objects/imdgam.o \
 		objects/imdpset.o \
 		objects/imdflux.o \
 		objects/imderr.o \
 		objects/imdresa.o \
 		objects/imdresb.o \
 		objects/imdresd.o \
 		objects/imdreset.o \
 		objects/imanewt.o \
 		objects/imagam.o \
 		objects/imapset.o \
 		objects/imaflux.o \
 		objects/imaerr.o \
 		objects/imaresa.o \
 		objects/imaresb.o \
 		objects/imaresd.o \
 		objects/imareset.o \
 		objects/mrdnewt.o \
 		objects/mrdgam.o \
 		objects/mrdpset.o \
 		objects/mrdflux.o \
 		objects/mrderr.o \
 		objects/mrdresa.o \
 		objects/mrdresb.o \
 		objects/mrdresd.o \
 		objects/mrdreset.o \
 		objects/mranewt.o \
 		objects/mragam.o \
 		objects/mrapset.o \
 		objects/mraflux.o \
 		objects/mraerr.o \
 		objects/mraresa.o \
 		objects/mraresb.o \
 		objects/mraresd.o \
 		objects/mrareset.o \
 		objects/oidnewt.o \
 		objects/oidgam.o \
 		objects/oidpset.o \
 		objects/oidflux.o \
 		objects/oiderr.o \
 		objects/oidresa.o \
 		objects/oidresb.o \
 		objects/oidresd.o \
 		objects/oidreset.o \
 		objects/oianewt.o \
 		objects/oiagam.o \
 		objects/oiapset.o \
 		objects/oiaflux.o \
 		objects/oiaerr.o \
 		objects/oiaresa.o \
 		objects/oiaresb.o \
 		objects/oiaresd.o \
 		objects/oiareset.o \

PRINT	      = pr

PROGRAM       = vr

SHELL	      = /bin/sh

SRCS	      = vr.f \
		les.f \
		archivr.f \
 		omdvr/omdnewt.f \
 		omdvr/omdgam.f \
 		omdvr/omdpset.f \
 		omdvr/omdflux.f \
 		omdvr/omderr.f \
 		omdvr/omdresa.f \
 		omdvr/omdresb.f \
 		omdvr/omdresd.f \
 		omdvr/omdreset.f \
 		omavr/omanewt.f \
 		omavr/omagam.f \
 		omavr/omapset.f \
 		omavr/omaflux.f \
 		omavr/omaerr.f \
 		omavr/omaresa.f \
 		omavr/omaresb.f \
 		omavr/omaresd.f \
 		omavr/omareset.f \
 		imdvr/imdnewt.f \
 		imdvr/imdgam.f \
 		imdvr/imdpset.f \
 		imdvr/imdflux.f \
 		imdvr/imderr.f \
 		imdvr/imdresa.f \
 		imdvr/imdresb.f \
 		imdvr/imdresd.f \
 		imdvr/imdreset.f \
 		imavr/imanewt.f \
 		imavr/imagam.f \
 		imavr/imapset.f \
 		imavr/imaflux.f \
 		imavr/imaerr.f \
 		imavr/imaresa.f \
 		imavr/imaresb.f \
 		imavr/imaresd.f \
 		imavr/imareset.f \
 		mrdvr/mrdnewt.f \
 		mrdvr/mrdgam.f \
 		mrdvr/mrdpset.f \
 		mrdvr/mrdflux.f \
 		mrdvr/mrderr.f \
 		mrdvr/mrdresa.f \
 		mrdvr/mrdresb.f \
 		mrdvr/mrdresd.f \
 		mrdvr/mrdreset.f \
 		mravr/mranewt.f \
 		mravr/mragam.f \
 		mravr/mrapset.f \
 		mravr/mraflux.f \
 		mravr/mraerr.f \
 		mravr/mraresa.f \
 		mravr/mraresb.f \
 		mravr/mraresd.f \
 		mravr/mrareset.f \
 		oidvr/oidnewt.f \
 		oidvr/oidgam.f \
 		oidvr/oidpset.f \
 		oidvr/oidflux.f \
 		oidvr/oiderr.f \
 		oidvr/oidresa.f \
 		oidvr/oidresb.f \
 		oidvr/oidresd.f \
 		oidvr/oidreset.f \
 		oiavr/oianewt.f \
 		oiavr/oiagam.f \
 		oiavr/oiapset.f \
 		oiavr/oiaflux.f \
 		oiavr/oiaerr.f \
 		oiavr/oiaresa.f \
 		oiavr/oiaresb.f \
 		oiavr/oiaresd.f \
 		oiavr/oiareset.f

all:		$(PROGRAM)

$(PROGRAM):     $(OBJS) $(LIBS)
		@echo "Linking $(PROGRAM) ..."
		@$(LD) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)
		@echo "done"

$(OBJS):	$(SRCS)
		gfortran -c $(FFLAGS) $(SRCS); mv *.o ./objects   

clean:;		@rm -f $(OBJS) core

clobber:;	@rm -f $(OBJS) $(PROGRAM) core tags

install:	$(PROGRAM)
		echo Installing $(PROGRAM) in $(DEST)
		if [ $(DEST) != . ]; then \
		(rm -f $(DEST)/$(PROGRAM); $(INSTALL) -f $(DEST) $(PROGRAM)); fi


