	PROGRAM VRR
C  PROGRAM TO READ AN OUTPUT FILE FROM VR.F
C   AND COMPUTE THE REABSORPTIVE FLUXES IN EACH SEGMENT
C
	INTEGER NWR,IWR(20),JWR(20),CHOP(7),DCHOP(7),NSEG
	REAL WRRES(8,20,50),RDRES(20),WRDL(8,20,50),DL(20),
     1    WREX(8,20,50),EX(20),TTIM,WRTIM(8,50),SCALE(20)
        CHARACTER*12 IPTFIL,OPTFIL,VARNAM
        CHARACTER*8 VNAME1(20),VNAME2(20),SWI
	CHARACTER*5 SEGNAMOM(2),SEGNAMIM(4),SEGNAMMR(2)
	CHARACTER*2 SWVR
C
C NWR-	NUMBER OF RESULTS TO BE REWRITTEN (UP TO 20)
C IWR,JWR-	LOCATION OF RESULT IN RESULT TABLE
C KXP-	NUMBER OF EXPERIMENTS (UP TO 50)
C CHOP- SPATIAL CHOP OF TUBULE SEGMENT OF INTEREST
C DCHOP-COARSER CHOP RESOLUTION FOR PRINTING (NOT USED HERE)
C WRRES(I,J,K)-	REABSORPTION OF J IN SEGMENT I DURING EXPT. K
C WRDL(I,J,K)-	DELIVERY OF J TO SEGMENT I DURING EXPT. K
C WREX(I,J,K)-	OUTFLOW OF J FROM SEGMENT I DURING EXPT. K
C WRTIM(I,K)-	TRANSIT TIME IN SEGMENT I DURING EXPT. K
C SWVR-	DIRECTING THE CALCULATION TO OM, IM, or MR VESSELS
C
	COMMON/TWR/NWR,IWR,JWR,TTIM,RDRES,DL,EX
	DATA SEGNAMOM /'OMDVR','OMAVR'/
	DATA SEGNAMIM /'OIDVR','IMDVR','IMAVR','OIAVR'/
	DATA SEGNAMMR /'MRDVR','MRAVR'/
C
	PRINT 2
    2   FORMAT(' TYPE THE INPUT FILENAME:',$)
	READ 4, IPTFIL
    4   FORMAT(A12)
C	PRINT 6
C    6   FORMAT(' TYPE THE OUTPUT FILENAME:',$)
C	READ 4, OPTFIL
	OPEN(1,FILE=IPTFIL)
	OPEN(2,FILE='xy.vrr')
	OPEN(3,FILE='secr.vrr')
C
	PRINT 10
   10   FORMAT(' Outer Medulla, Inner Medulla, or Medullary Ray
     1    (om/im/mr): ',$)
	READ *, SWVR
	IF (SWVR.EQ.'om') THEN
	NSEG=2
	OPEN(4,FILE='vrmeshom.dat')
	ELSE IF (SWVR.EQ.'im') THEN
	NSEG=4
	OPEN(4,FILE='vrmeshim.dat')
	ELSE IF (SWVR.EQ.'mr') THEN
	NSEG=2
	OPEN(4,FILE='vrmeshmr.dat')
        ELSE
	PRINT 18
   18   FORMAT (' NO VESSEL SELECTED')
	STOP
	ENDIF
C
	PRINT 3
    3   FORMAT(' MESH SPACING - DATA FILE OR INTERACTIVE? (d/i):',$)
	READ *, SWI
	IF (SWI.EQ.'i') GO TO 7
	READ (4,5) (CHOP(L),DCHOP(L),L=1,NSEG)
    5   FORMAT(2I5)
	GO TO 12
C
    7   DO 11 K=1,NSEG
	IF (SWVR.EQ.'om') THEN
	PRINT 8, SEGNAMOM(K)
	ELSE IF (SWVR.EQ.'im') THEN
	PRINT 8, SEGNAMIM(K)
	ELSE IF (SWVR.EQ.'mr') THEN
	PRINT 8, SEGNAMMR(K)
	ENDIF
    8   FORMAT(A4,' SPATIAL CHOP, AND PRINT SPACING:',$) 
	READ *, CHOP(K),DCHOP(K)
   11   CONTINUE
C
   12   DO 13 L=1,NSEG
   13   CHOP(L)=CHOP(L)+1
C
C
	PRINT 500
  500   FORMAT(' IS INPUT FROM A DATA FILE OR INTERACTIVE? (d/i): ',$)
	READ 30, SWI
  510   IF (SWI.EQ.'i') GO TO 15
	PRINT 516
  516   FORMAT(' TYPE THE VARIABLE FILENAME:',$)
	READ 514, VARNAM
  514   FORMAT(A12)
	OPEN(5,FILE=VARNAM)
	READ (5,515) NWR
  515   FORMAT(3X,I2)
	DO 525 KWR=1,NWR
  525   READ (5,530) VNAME1(KWR),VNAME2(KWR),SCALE(KWR)
  530   FORMAT(2A8,E10.2)
	GO TO 801
C
C
   15   PRINT 16
   16   FORMAT(' TYPE THE NUMBER OF VARIABLES TO BE REWRITTEN')
	READ *, NWR
	DO 50 KWR=1,NWR
	VNAME1(KWR)='fkc'
	PRINT 20, KWR
   20   FORMAT(' TYPE THE SPECIES NUMBER',I2,":",2X,$) 
	READ 30, VNAME2(KWR)
	PRINT 22, KWR
   22   FORMAT(' TYPE THE SCALE NUMBER',I2,":",2X,$) 
	READ *, SCALE(KWR)
   30   FORMAT(A8)
   50   CONTINUE
C
C THE WRITTEN VARIABLES HAVE BEEN SPECIFIED, AS HAS TUBULE SEGMENTATION
C
  801   DO 900 KXP=1,100
C
C DATA FOR EACH SEGMENT IS READ
C
	DO 820 ISEG=1,NSEG
	DO 810 KWR=1,NWR
  810   CALL SELEC 
     1   (VNAME1(KWR),VNAME2(KWR),IWR(KWR),JWR(KWR),CHOP(ISEG))
	CALL RDSEG(CHOP(ISEG),*811,*901)
  811   DO 817 J=1,NWR
	WRDL(ISEG,J,KXP)=SCALE(J)*DL(J)
	WREX(ISEG,J,KXP)=SCALE(J)*EX(J)
  817   WRRES(ISEG,J,KXP)=SCALE(J)*RDRES(J)
	WRTIM(ISEG,KXP)=TTIM
  820   CONTINUE
C	
C THIS IS THE TOTAL VR
C
	WRTIM(NSEG+1,KXP) = 0.D0
	DO 856 ISEG=1,NSEG
  856   WRTIM(NSEG+1,KXP) = WRTIM(NSEG+1,KXP) + WRTIM(ISEG,KXP)
	DO 858 J=1,NWR
	WRRES(NSEG+1,J,KXP) = 0.D0
	DO 857 ISEG=1,NSEG
  857   WRRES(NSEG+1,J,KXP) = WRRES(NSEG+1,J,KXP) + WRRES(ISEG,J,KXP)
  858   CONTINUE
C
  900   CONTINUE
C
C WRRES HAS BEEN FILLED. 
C
  901   KXP=KXP-1


	IF (SWVR.EQ.'om') THEN
	WRITE (2,902) (SEGNAMOM(I),I=1,NSEG)
	ELSE IF (SWVR.EQ.'im') THEN
	WRITE (2,902) (SEGNAMIM(I),I=1,NSEG)
	ELSE IF (SWVR.EQ.'mr') THEN
	WRITE (2,902) (SEGNAMMR(I),I=1,NSEG)
	ENDIF
  902   FORMAT(///,10X,7(A5,7X),'TOTAL')
	DO 910 K=1,KXP
	WRITE (2,903) 
  903   FORMAT(/,2X,'absolute delivery',/)
	DO 923 J=1,NWR
  923   WRITE (2,915) VNAME2(J),(WRDL(ISEG,J,K),ISEG=1,NSEG),
     1     WREX(NSEG,J,K)
	WRITE (2,904) 
  904   FORMAT(/,2X,'absolute reabsorption',/)
	DO 924 J=1,NWR
  924   WRITE (2,915) VNAME2(J),(WRRES(ISEG,J,K),ISEG=1,NSEG),
     1     WRRES(NSEG+1,J,K)
	WRITE (2,905) 
  905   FORMAT(/,2X,'reabsorption relative to segmental delivery',/)
	DO 925 J=1,NWR
  925   WRITE (2,916) VNAME2(J),
     1     (WRRES(ISEG,J,K)/WRDL(ISEG,J,K),ISEG=1,NSEG),
     1     WRRES(NSEG+1,J,K)/WRDL(1,J,K)
	WRITE (2,906) 
  906   FORMAT(/,2X,'reabsorption relative to vessel delivery',/)
	DO 926 J=1,NWR
  926   WRITE (2,916) VNAME2(J),
     1     (WRRES(ISEG,J,K)/WRDL(1,J,K),ISEG=1,NSEG),
     1     WRRES(NSEG+1,J,K)/WRDL(1,J,K)
	DO 928 J=1,NWR
  928   WRITE (3,918) (-WRRES(ISEG,J,K),ISEG=1,NSEG+1)
  910   CONTINUE
  915   FORMAT (1X,A5,8E12.4)
  916   FORMAT (1X,A5,8F12.4)
  917   FORMAT (6X,8F12.4)
  918   FORMAT (8E16.8)
C
	STOP
	END
C
C
        SUBROUTINE SELEC (VNAME1,VNAME2,IWR,JWR,IC)
C
	INTEGER NWR,IWR,JWR,IC
        CHARACTER*8 VNAME1,VNAME2
C
C
	IF(VNAME1.EQ.'vc') THEN 
        IWR=1+2*IC
        JWR=2
        GO TO 800
        ELSE IF(VNAME1.EQ.'pc') THEN 
        IWR=1+IC
        JWR=2
        GO TO 800
        ELSE IF(VNAME1.EQ.'cc') THEN 
        IWR=1+IC
        JWR=3
        GO TO 200
	ELSE IF(VNAME1.EQ.'phc') THEN 
        IWR=1+2*IC
        JWR=13
        GO TO 800
	ELSE IF(VNAME1.EQ.'xc') THEN 
        IWR=1+2*IC
        JWR=3
        GO TO 200
	ELSE IF(VNAME1.EQ.'fvc') THEN 
        IWR=1+3*IC
	JWR=2
        GO TO 800
	ELSE IF(VNAME1.EQ.'fkc') THEN 
        IWR=1+3*IC
	JWR=3
        GO TO 200
	ELSE IF(VNAME1.EQ.'fbc') THEN 
        IWR=1+3*IC
	JWR=13
        GO TO 800
	ELSE IF(VNAME1.EQ.'hct') THEN 
        IWR=1+3*IC
	JWR=14
        GO TO 800
C
	ELSE IF(VNAME1.EQ.'ps') THEN 
        IWR=1
	JWR=2
        GO TO 800
	ELSE IF(VNAME1.EQ.'cs') THEN 
        IWR=1
	JWR=3
        GO TO 200
	ELSE IF(VNAME1.EQ.'phs') THEN 
        IWR=1
	JWR=13
        GO TO 800
	ELSE IF(VNAME1.EQ.'fvcs') THEN 
        IWR=2+4*IC
	JWR=2
        GO TO 800
	ELSE IF(VNAME1.EQ.'fkcs') THEN 
        IWR=2+4*IC
	JWR=3
        GO TO 200
C
	ELSE IF(VNAME1.EQ.'apr') THEN 
        IWR=1+4*IC
	JWR=2
        GO TO 200
	ELSE IF(VNAME1.EQ.'cur') THEN 
        IWR=2+4*IC
	JWR=13
        GO TO 800
	ELSE IF(VNAME1.EQ.'h') THEN 
        IWR=2+5*IC
	JWR=3
        GO TO 800
	ELSE IF(VNAME1.EQ.'hgb') THEN 
        GO TO 250
        ELSE
        PRINT 40
   40   FORMAT(' NO SUCH VARIABLE NAME, TRY AGAIN')
        STOP
        ENDIF
C
C
  200   CONTINUE
	IF(VNAME2.EQ.'vol') THEN 
        JWR=JWR-1
	GO TO 800
	ELSE IF(VNAME2.EQ.'na') THEN 
        JWR=JWR+0
	GO TO 800
	ELSE IF(VNAME2.EQ.'k') THEN 
        JWR=JWR+1
	GO TO 800
	ELSE IF(VNAME2.EQ.'cl') THEN 
        JWR=JWR+2
	GO TO 800
	ELSE IF(VNAME2.EQ.'hco3') THEN 
        JWR=JWR+3
	GO TO 800
	ELSE IF(VNAME2.EQ.'hpo') THEN 
        JWR=JWR+4
	GO TO 800
	ELSE IF(VNAME2.EQ.'h2po') THEN 
        JWR=JWR+5
	GO TO 800
	ELSE IF(VNAME2.EQ.'urea') THEN 
        JWR=JWR+6
	GO TO 800
	ELSE IF(VNAME2.EQ.'nh4') THEN 
        JWR=JWR+7
	GO TO 800
	ELSE IF(VNAME2.EQ.'hco2') THEN 
        JWR=JWR+8
	GO TO 800
	ELSE IF(VNAME2.EQ.'gluc') THEN 
        JWR=JWR+9
	GO TO 800
	ELSE IF(VNAME2.EQ.'prot') THEN 
        JWR=13
	GO TO 800
	ELSE IF(VNAME2.EQ.'osm') THEN 
        IWR=1+2*IC
        JWR=13
	GO TO 800
        ELSE IF(VNAME2.EQ.'ta') THEN
        JWR=11
          IF(VNAME1.EQ.'cc') THEN
          IWR=2+5*IC
	  GO TO 800
          ELSE IF(VNAME1.EQ.'fkc') THEN
          IWR=2+6*IC
	  GO TO 800
          ELSE IF(VNAME1.EQ.'apr') THEN
          JWR=13
	  GO TO 800
          ELSE
          PRINT 235
  235     FORMAT(' CANT FIND VNAME1 MATCHING TA, TRY AGAIN')
            STOP
          ENDIF
        ELSE IF(VNAME2.EQ.'nae') THEN
        JWR=12
          IF(VNAME1.EQ.'cc') THEN
          IWR=2+5*IC
	  GO TO 800
          ELSE IF(VNAME1.EQ.'fkc') THEN
          IWR=2+6*IC
	  GO TO 800
          ELSE IF(VNAME1.EQ.'apr') THEN
          JWR=14
	  GO TO 800
          ELSE
          PRINT 236
  236     FORMAT(' CANT FIND VNAME1 MATCHING NAE, TRY AGAIN')
            STOP
          ENDIF
        ELSE
        PRINT 240
  240   FORMAT(' NO SUCH SOLUTE NAME, TRY AGAIN')
        STOP
        ENDIF
C
C
C A HGB SPECIES HAS BEEN DESIGNATED
C
  250   CONTINUE
	IF(VNAME2.EQ.'onh2') THEN 
        IWR=2+5*IC
        JWR=4
	GO TO 800
	ELSE IF(VNAME2.EQ.'nh2') THEN 
        IWR=2+5*IC
        JWR=5
	GO TO 800
	ELSE IF(VNAME2.EQ.'onh3') THEN 
        IWR=2+5*IC
        JWR=6
	GO TO 800
	ELSE IF(VNAME2.EQ.'nh3') THEN 
        IWR=2+5*IC
        JWR=7
	GO TO 800
	ELSE IF(VNAME2.EQ.'onhco2') THEN 
        IWR=2+5*IC
        JWR=8
	GO TO 800
	ELSE IF(VNAME2.EQ.'nhco2') THEN 
        IWR=2+5*IC
        JWR=9
	GO TO 800
	ELSE IF(VNAME2.EQ.'oxh') THEN 
        IWR=2+5*IC
        JWR=2
	GO TO 800
	ELSE IF(VNAME2.EQ.'xh') THEN 
        IWR=2+6*IC
        JWR=3
	GO TO 800
	ELSE IF(VNAME2.EQ.'ox') THEN 
        IWR=2+6*IC
        JWR=4
	GO TO 800
	ELSE IF(VNAME2.EQ.'x') THEN 
        IWR=2+6*IC
        JWR=5
	GO TO 800
	ELSE IF(VNAME2.EQ.'oyh') THEN 
        IWR=2+6*IC
        JWR=6
	GO TO 800
	ELSE IF(VNAME2.EQ.'yh') THEN 
        IWR=2+6*IC
        JWR=7
	GO TO 800
	ELSE IF(VNAME2.EQ.'oy') THEN 
        IWR=2+6*IC
        JWR=8
	GO TO 800
	ELSE IF(VNAME2.EQ.'y') THEN 
        IWR=2+6*IC
        JWR=9
	GO TO 800
        ELSE
        PRINT 260
  260   FORMAT(' NO SUCH HGB NAME, TRY AGAIN')
        STOP
        ENDIF
C
  800   RETURN
        END
C
C
	SUBROUTINE RDSEG(CHOP,*,*)
C PROGRAM TO READ THE TUBULE SEGMENT RECORDS AND OUTPUT THE SELECTED VARIABLES
C
	INTEGER NWR,IWR(20),JWR(20),CHOP
	REAL RES(4803,16),TIME,RDRES(20),DL(20),EX(20)
C
	COMMON/TWR/NWR,IWR,JWR,TIME,RDRES,DL,EX
C
        IC = CHOP
  300   READ (1,310,END=360) TIME
  310   FORMAT (2(/),11X,F15.4)
	READ (1,320) ((RES(I,J),J=1,13),I=1,IC)
	READ (1,325) ((RES(I,J),J=1,13),I=1+IC,2*IC)
	READ (1,325) ((RES(I,J),J=1,13),I=1+2*IC,3*IC)
C
	READ (1,330) ((RES(I,J),J=1,14),I=1+3*IC,4*IC)
	READ (1,335) (RES(1+4*IC,J),J=2,14)
	READ (1,340) ((RES(I,J),J=1,13),I=2+4*IC,1+5*IC)
	READ (1,345) 
     1   ((RES(I,J),J=1,9),RES(I,11),RES(I,12),I=2+5*IC,1+6*IC)
	READ (1,350) 
     1   ((RES(I,J),J=1,9),RES(I,11),RES(I,12),I=2+6*IC,1+7*IC)
  320   FORMAT (///,(3X,F8.6,12F11.6))
  325   FORMAT (///,(3X,F8.6,12F11.6))
  330   FORMAT (///,(3X,F8.6,13F11.6))
  335   FORMAT (//,(11X,13F11.6))
  340   FORMAT (///,(3X,F8.6,12D11.3))
  345   FORMAT (6(/),(3X,F8.6,F10.6,D12.4,6F11.6,11X,2F11.6))
  350   FORMAT (///,(3X,F8.6,8F11.6,11X,2F11.6))
C
	DO 355 J=1,NWR
	DL(J) = RES(IWR(J),JWR(J))
	EX(J) = RES(IWR(J)+CHOP-1,JWR(J))
  355   RDRES(J)=RES(IWR(J),JWR(J)) - RES(IWR(J)+CHOP-1,JWR(J))
C
	RETURN 1
  360   RETURN 2
	END
C
