	PROGRAM REBOUND
C
C TO READ BOUND.DAT AND OUTPUT POINTS FOR ABCISSA(S) IN PLOTTING
C
	INTEGER SOLS
	DOUBLE PRECISION XY(1601,2)
C
C LUMINAL AND PERITUBULAR PARAMETERS
	DOUBLE PRECISION DT,
     1   VM,PM,CM(12),IMPM,
     1   VS(2),PS(2),CS(12,2),IMPS(2),FVM
C
	INTEGER NWR,IWR(2),JWR(2)
	CHARACTER*5 VNAME1,VNAME2
	DOUBLE PRECISION VMAT(16,3)
C
	OPEN (20,FILE='dcbound.xy')
	OPEN (22,FILE='dcbound.dat')
C
	SOLS=12
C
C  SOLUTE INDEX:
C	1-	NA+
C	2-	K+
C	3-	CL-
C	4-	HCO3-
C	5-	H2CO3
C	6-	CO2
C	7-	HPO4--
C	8-	H2PO4-
C	9-	UREA
C	10-	NH3
C	11-	NH4+
C	12-	H+
C
	PRINT 10
   10   FORMAT(' PRINT THE NUMBER OF VARIABLES TO BE SELECTED')
	READ *, NWR
	DO 800 KWR=1,NWR
   15   PRINT 20, KWR
   20   FORMAT(' PRINT THE NAME OF VARIABLE NUMBER-',I2)
	READ 30, VNAME1
   30   FORMAT(A4)
C
C
	IF(VNAME1.EQ.'fvm') THEN
	IWR(KWR)=1
	JWR(KWR)=1
	ELSE IF(VNAME1.EQ.'vm') THEN
	IWR(KWR)=2
	JWR(KWR)=1
	ELSE IF(VNAME1.EQ.'pm') THEN
	IWR(KWR)=3
	JWR(KWR)=1
	ELSE IF(VNAME1.EQ.'impm') THEN
	IWR(KWR)=4
	JWR(KWR)=1
	ELSE IF(VNAME1.EQ.'cm') THEN
	IWR(KWR)=5
	JWR(KWR)=1
	GO TO 200
	ELSE IF(VNAME1.EQ.'vs0') THEN
	IWR(KWR)=2
	JWR(KWR)=2
	ELSE IF(VNAME1.EQ.'ps0') THEN
	IWR(KWR)=3
	JWR(KWR)=2
	ELSE IF(VNAME1.EQ.'imps0') THEN
	IWR(KWR)=4
	JWR(KWR)=2
	ELSE IF(VNAME1.EQ.'cs0') THEN
	IWR(KWR)=5
	JWR(KWR)=2
	GO TO 200
	ELSE IF(VNAME1.EQ.'vs1') THEN
	IWR(KWR)=2
	JWR(KWR)=3
	ELSE IF(VNAME1.EQ.'ps1') THEN
	IWR(KWR)=3
	JWR(KWR)=3
	ELSE IF(VNAME1.EQ.'imps1') THEN
	IWR(KWR)=4
	JWR(KWR)=3
	ELSE IF(VNAME1.EQ.'cs1') THEN
	IWR(KWR)=5
	JWR(KWR)=3
	GO TO 200
	ELSE
	PRINT 35
   35   FORMAT (' NO SUCH VARIABLE, TRY AGAIN')
	GO TO 15
	ENDIF
	GO TO 700
C
C
  200   PRINT 201
  201   FORMAT(' PRINT THE SPECIES')
	READ 30, VNAME2
C
	IF(VNAME2.EQ.'na') THEN
	 IWR(KWR)=IWR(KWR)+0
	ELSE IF(VNAME2.EQ.'k') THEN
	 IWR(KWR)=IWR(KWR)+1
	ELSE IF(VNAME2.EQ.'cl') THEN
	 IWR(KWR)=IWR(KWR)+2
	ELSE IF(VNAME2.EQ.'hco3') THEN
	 IWR(KWR)=IWR(KWR)+3
	ELSE IF(VNAME2.EQ.'h2co3') THEN
	 IWR(KWR)=IWR(KWR)+4
	ELSE IF(VNAME2.EQ.'co2') THEN
	 IWR(KWR)=IWR(KWR)+5
	ELSE IF(VNAME2.EQ.'hpo4') THEN
	 IWR(KWR)=IWR(KWR)+6
	ELSE IF(VNAME2.EQ.'h2po4') THEN
	 IWR(KWR)=IWR(KWR)+7
	ELSE IF(VNAME2.EQ.'urea') THEN
	 IWR(KWR)=IWR(KWR)+8
	ELSE IF(VNAME2.EQ.'nh3') THEN
	 IWR(KWR)=IWR(KWR)+9
	ELSE IF(VNAME2.EQ.'nh4') THEN
	 IWR(KWR)=IWR(KWR)+10
	ELSE
	PRINT 235
  235   FORMAT (' NO SUCH SPECIES, TRY AGAIN')
	GO TO 200
	ENDIF
C
  700   CONTINUE
  800   CONTINUE
C
C
C BOUNDARY VALUES,ACTIVE TRANSPORT,AND THE TIME INCREMENT ARE
C READ. THE TIME STEP WILL CYCLE FROM THIS POINT.
C
	DO 900 NTAB=1,1601
	READ(22,50,END=901) DT,FVM,
     1  VM,VS(1),VS(2),PM,PS(1),PS(2),IMPM,IMPS(1),IMPS(2),
     1  (CM(I),CS(I,1),CS(I,2),I=1,SOLS-1)
   50   FORMAT (2D12.4,/,3F8.4,/,3F8.4,/,3F8.4,/,(3F14.9))
C
	VMAT(1,1)=FVM
	VMAT(2,1)=VM
	VMAT(3,1)=PM
	VMAT(4,1)=IMPM
	VMAT(2,2)=VS(1)
	VMAT(3,2)=PS(1)
	VMAT(4,2)=IMPS(1)
	VMAT(2,3)=VS(2)
	VMAT(3,3)=PS(2)
	VMAT(4,3)=IMPS(2)
	DO 40 I=1,SOLS
	VMAT(4+I,1)=CM(I)
	VMAT(4+I,2)=CS(I,1)
   40   VMAT(4+I,3)=CS(I,2)
C
	DO 140 KWR=1,NWR
	XY(NTAB,KWR)=VMAT(IWR(KWR),JWR(KWR))
  140   CONTINUE
C
  900   CONTINUE
  901   NTAB=NTAB-1
C
	DO 150 ITAB=1,NTAB
  150   WRITE(20,155) (XY(ITAB,KWR),KWR=1,NWR)
  155   FORMAT(2E16.8)
C
	STOP
	END
