F95 = gfortran

FFLAGS	      = -g -w

CFLAGS	      = 

DEST	      = objects

EXTHDRS	      =

HDRS	      =

INSTALL	      = install

LD	      = gfortran

LDFLAGS	      = 

LIBS	      =

MAKEFILE      = Makefile

OBJS	      = objects/dn.o \
 		objects/dctnewt.o \
 		objects/dctgam.o \
 		objects/dctpset.o \
 		objects/dctptim.o \
 		objects/dctflux.o \
 		objects/dcterr.o \
 		objects/dctresa.o \
 		objects/dctresb.o \
 		objects/dctresc.o \
 		objects/dctresd.o \
 		objects/dctpick.o \
 		objects/dcreset.o \
 		objects/cntnewt.o \
 		objects/cntgam.o \
 		objects/cntpset.o \
 		objects/cntptim.o \
 		objects/cntflux.o \
 		objects/cnterr.o \
 		objects/cntresa.o \
 		objects/cntresb.o \
 		objects/cntresc.o \
 		objects/cntresd.o \
 		objects/cntpick.o \
 		objects/cnreset.o \
 		objects/cctnewt.o \
 		objects/cctgam.o \
 		objects/cctpset.o \
 		objects/cctptim.o \
 		objects/cctflux.o \
 		objects/ccterr.o \
 		objects/cctresa.o \
 		objects/cctresb.o \
 		objects/cctresc.o \
 		objects/cctresd.o \
 		objects/cctpick.o \
 		objects/ccreset.o \
 		objects/omctnewt.o \
 		objects/omctgam.o \
 		objects/omctpset.o \
 		objects/omctptim.o \
 		objects/omctflux.o \
 		objects/omcterr.o \
 		objects/omctresa.o \
 		objects/omctresb.o \
 		objects/omctresc.o \
 		objects/omctresd.o \
 		objects/omctpick.o \
 		objects/omcreset.o \
 		objects/ompctnewt.o \
 		objects/ompctgam.o \
 		objects/ompctpset.o \
 		objects/ompctptim.o \
 		objects/ompctflux.o \
 		objects/ompcterr.o \
 		objects/ompctresa.o \
 		objects/ompctresb.o \
 		objects/ompctresc.o \
 		objects/ompctresd.o \
 		objects/ompctpick.o \
 		objects/ompctreset.o \
 		objects/imctnewt.o \
 		objects/imctgam.o \
 		objects/imctpset.o \
 		objects/imctptim.o \
 		objects/imctflux.o \
 		objects/imcterr.o \
 		objects/imctresa.o \
 		objects/imctresb.o \
 		objects/imctresc.o \
 		objects/imctresd.o \
 		objects/imctpick.o \
 		objects/imcreset.o \
		objects/hksub.o \
		objects/ae1.o \
		objects/nhe3.o \
		objects/tsc.o \
		objects/les8.o \
		objects/eqlib.o

PRINT	      = pr

PROGRAM       = dn

SHELL	      = /bin/sh

SRCS	      = dn.f \
 		dct/dctnewt.f \
 		dct/dctgam.f \
 		dct/dctpset.f \
 		dct/dctptim.f \
 		dct/dctflux.f \
 		dct/dcterr.f \
 		dct/dctresa.f \
 		dct/dctresb.f \
 		dct/dctresc.f \
 		dct/dctresd.f \
 		dct/dctpick.f \
 		dct/dcreset.f \
 		cnt/cntnewt.f \
 		cnt/cntgam.f \
 		cnt/cntpset.f \
 		cnt/cntptim.f \
 		cnt/cntflux.f \
 		cnt/cnterr.f \
 		cnt/cntresa.f \
 		cnt/cntresb.f \
 		cnt/cntresc.f \
 		cnt/cntresd.f \
 		cnt/cntpick.f \
 		cnt/cnreset.f \
 		cct/cctnewt.f \
 		cct/cctgam.f \
 		cct/cctpset.f \
 		cct/cctptim.f \
 		cct/cctflux.f \
 		cct/ccterr.f \
 		cct/cctresa.f \
 		cct/cctresb.f \
 		cct/cctresc.f \
 		cct/cctresd.f \
 		cct/cctpick.f \
 		cct/ccreset.f \
 		omct/omctnewt.f \
 		omct/omctgam.f \
 		omct/omctpset.f \
 		omct/omctptim.f \
 		omct/omctflux.f \
 		omct/omcterr.f \
 		omct/omctresa.f \
 		omct/omctresb.f \
 		omct/omctresc.f \
 		omct/omctresd.f \
 		omct/omctpick.f \
 		omct/omcreset.f \
 		ompct/ompctnewt.f \
 		ompct/ompctgam.f \
 		ompct/ompctpset.f \
 		ompct/ompctptim.f \
 		ompct/ompctflux.f \
 		ompct/ompcterr.f \
 		ompct/ompctresa.f \
 		ompct/ompctresb.f \
 		ompct/ompctresc.f \
 		ompct/ompctresd.f \
 		ompct/ompctpick.f \
 		ompct/ompctreset.f \
 		imct/imctnewt.f \
 		imct/imctgam.f \
 		imct/imctpset.f \
 		imct/imctptim.f \
 		imct/imctflux.f \
 		imct/imcterr.f \
 		imct/imctresa.f \
 		imct/imctresb.f \
 		imct/imctresc.f \
 		imct/imctresd.f \
 		imct/imctpick.f \
 		imct/imcreset.f \
		hksub.f \
		ae1.f \
		nhe3.f \
		tsc.f \
		les8.f \
		eqlib.f



all:		$(PROGRAM)

$(PROGRAM):     $(OBJS) $(LIBS)
		@echo "Linking $(PROGRAM) ..."
		@$(LD) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)
		@echo "done"

$(OBJS):	$(SRCS)
		gfortran -c $(FFLAGS) $(SRCS); mv *.o ./objects   

clean:;		@rm -f $(OBJS) core

clobber:;	@rm -f $(OBJS) $(PROGRAM) core tags

install:	$(PROGRAM)
		echo Installing $(PROGRAM) in $(DEST)
		if [ $(DEST) != . ]; then \
		(rm -f $(DEST)/$(PROGRAM); $(INSTALL) -f $(DEST) $(PROGRAM)); fi


