	PROGRAM ACR
C BCR-PROGRAM TO CREATE AN ABCISSA
C
	INTEGER TLIM
	DOUBLE PRECISION C,DC
C
	OPEN (19,FILE='abcis.dat')
C
	PRINT 10
   10   FORMAT('INITIAL VALUE= ',$)
	READ *, C
	PRINT 12
   12   FORMAT('INCREMENT= ',$)
	READ *, DC
	PRINT 14
   14   FORMAT('STEP NUMBER= ',$)
	READ *, TLIM
C
	DO 40 I=1,TLIM
	WRITE (19,45) C
	C = C + DC
   40   CONTINUE
   45   FORMAT(D16.8)
C
	STOP
	END
